services:
  vite:
    build: .
    volumes:
      - type: bind
        source: ./vue
        target: /opt/app/vue
      - type: volume
        source: node_modules
        target: /opt/app/vue/node_modules
    ports:
      - "3000:5173"

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/vue/node_modules
      o: bind
